### ISSUE TITLE
omegawiki.org down

### ISSUE THREAD

**Issue by martino-vic** [concepticon/concepticon#50]
Some concepts are linking to omegawiki.org -- which gives me a 502 bad gateway error.
Might just be a temporal issue, or the project has been moved to another site, or abandoned. Thought it would be good to mark this as an open issue, just in case.

**Comment by LinguList** [comment]
We are at the moment modifying the design. Links to metadata will be done exclusively by the norare project, so the dead link should be investigated there.

**Comment by xrotwang** [comment]
Seems to be back online.
